### ISSUE TITLE
Error in quotes

### ISSUE THREAD

**Issue by cedrusmfaizan** [12beesinatrenchcoat/incorrect-quotes-generator#14]
Hey, I'm trying to generate quotes, but facing issue in button, 
then I tried this one: https://technmind.com/incorrect-quotes-generator/

**Comment by 12beesinatrenchcoat** [comment]
You're going to have to be more specific - what issue are you facing with the button?

> then I tried this one: https://technmind.com/incorrect-quotes-generator/
This incorrect quotes generator is completely unaffiliated with me - I made the one at https://12beesinatrenchcoat.github.io/incorrect-quotes-generator. If you're talking about another one, I don't think I can help with it.

**Comment by 12beesinatrenchcoat** [comment]
It's been a while, and so for some arbitrary reason to "keep this repository clean", I'll be closing this. Please feel free to comment again with more details if you want me to reopen it (or reopen it yourself if you can)!
Thanks!
