### ISSUE TITLE
"Random number of characters" always gives quotes with minimum number of people

### ISSUE THREAD

**Issue by Typherr** [12beesinatrenchcoat/incorrect-quotes-generator#16]

**Comment by 12beesinatrenchcoat** [comment]
After a bit of testing, I *am* able to reproduce this. Will investigate once I get back to my laptop.

**Comment by 12beesinatrenchcoat** [comment]
*Should* be fixed with https://github.com/12beesinatrenchcoat/incorrect-quotes-generator/commit/8a5c497ad0395d02f83f4f8f60d06b9c5da1c09d, yell at me if it isn't! (I made a typo, set the maximum characters variable to the minimum characters input's value.)

**Comment by 12beesinatrenchcoat** [comment]
aaand never mind please hold

**Comment by 12beesinatrenchcoat** [comment]
Made another typo, but it *should* actually be fixed now. For real this time. https://github.com/12beesinatrenchcoat/incorrect-quotes-generator/commit/9108cb1a7011a65f3ed57f7ca8758f9577d498f2
